### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Asuranceturix** [t-mat/lz4mt#1]
I have been trying to compress a very large directory (300 GB) using tar and lz4mt on a 64-bit Ubuntu 12.10 Linux:

`tar cf - <dir> | lz4mt -hc stdin <archive>`

However, lz4mt ends up filling up the entire available memory and then some. This does not happen using the reference lz4 implementation. If you need me to provide any more details, just ask.

**Comment by t-mat** [comment]
Thank you for testing.

It is a defect of lz4mt. I'll fix it.

##### repro on ubuntu 13.10

```
truncate -s 128G test.bin
lz4mt -hc test.bin
```

**Comment by t-mat** [comment]
I've committed ddc7146fb1e95de3682da2f314ee9847215ad4ef to fix this issue.
Please try it.

**Comment by Asuranceturix** [comment]
Looks good, memory usage is stable throughout the whole execution of the program. Thanks for fixing it!

**Comment by t-mat** [comment]
thanks !
