### ISSUE TITLE
What is the particular goal of this project ?

### ISSUE THREAD

**Issue by t-mat** [t-mat/lz4mt#29]
From @rdp's [comment](https://github.com/t-mat/lz4mt/commit/e3a35932aa9ccf50ed5285caee53c50e02d8f740#commitcomment-9504433)

> lz4 already supports some kind of multi-threaded'ism doesn't it?

Yes, and no. There are 3 kind of lz4. (1) `lz4` command line utility, (2) [Early lz4](http://fastcompression.blogspot.com/p/lz4.html), (3) lz4 algorithm, framing format and its library.
1. No. If you refer `lz4` as lz4 command line utility (`lz4cli.c`), answer is no.
2. Yes. The early version of LZ4 has multithread capability. But it only runs on Windows and its code has not released unfortunately.
3. Yes and no. lz4 framing format and its libraries were designed for multithread applications. But it does not provide direct multithread functions like [blosc](http://www.blosc.org/).

> What is the particular goal of this project, compared to that?

Hopefully, running faster by relatively simple and standard compliant portable code.

**Comment by rdp** [comment]
perhaps the readme could call out a few of these facts, for questioning followers like myself? :)

**Comment by t-mat** [comment]
Thanks. I'll consider about it.
