### ISSUE TITLE
Threaded compression and decompression for LZ4 Info

### ISSUE THREAD

**Issue by ghost** [t-mat/lz4mt#33]
Hello t-mat,

I just wanted to inform, that I implemented parrallel compression and decompression for Lz4 in C.

The needed size information can be written into an skippable frame. So the data chunks can be read asynchronly as needed for each thread ;-)

The source for it can be found in this repo: https://github.com/mcmilk/zstdmt

with best regards, milky

**Comment by t-mat** [comment]
Hi @mcmilk , 
Thanks for the information :)
Creative usage of skippable frame is a neat trick!

**Comment by MarcusJohnson91** [comment]
@mcmilk I've been thinking about doing something for my FLAC decoder but wasn't 100% about how to do it, thanks.

**Comment by ghost** [comment]
Sorry, I re-opened it some day... :(
